import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';

class ReportGenerator {
  static Future<File> generatePDF(Map<String, dynamic> data) async {
    final pdf = pw.Document();

    // Desain PDF Formal
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(level: 0, child: pw.Text("InsightMind - Health Screening Report")),
              pw.SizedBox(height: 20),
              pw.Text("Tanggal: ${DateTime.now().toString()}"),
              pw.Divider(),
              pw.SizedBox(height: 10),
              pw.Text("Hasil Analisis AI:", style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18)),
              pw.Bullet(text: "Skor Akhir: ${data['score']}"),
              pw.Bullet(text: "Tingkat Risiko: ${data['risk_level']}"),
              pw.SizedBox(height: 20),
              pw.Text("Catatan Profesional:", style: pw.TextStyle(fontStyle: pw.FontStyle.italic)),
              pw.Text("Laporan ini dihasilkan secara otomatis oleh sistem AI InsightMind berdasarkan kuesioner dan data sensor."),
              pw.Spacer(),
              pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.Text("Generated by InsightMind App", style: pw.TextStyle(color: PdfColors.grey)),
              ),
            ],
          );
        },
      ),
    );

    // Simpan ke file temporary
    final output = await getTemporaryDirectory();
    final file = File("${output.path}/Report_${DateTime.now().millisecondsSinceEpoch}.pdf");
    await file.writeAsBytes(await pdf.save());
    return file;
  }
}